### ISSUE TITLE
反向代理可以访问，但搜索时出现403错误。

### ISSUE THREAD

**Issue by magic282** [cuber/ngx_http_google_filter_module#100]
Hi，

我没有用这个项目来搭建反代，我是用的自己之前弄的一个简单的配置文件。

现在遇到的问题是可以访问google，但是搜索时会跳转到类似https://ipv4.google.com/sorry/IndexRedirect?continue=https://www.google.com/search%3Fsite%3D%
这样的地址，并显示403错误，如图：

![fuck_google](https://cloud.githubusercontent.com/assets/2285145/14352698/5f251628-fd08-11e5-952b-96a7862b8131.PNG)

请问这是什么原因呢？

谢谢。

**Comment by wangqiliang** [comment]
你是不是IPv4/v6协议栈没有设置好呢
