### ISSUE TITLE
[alert] http request count is zero while sending to client

### ISSUE THREAD

**Issue by alexyangjie** [cuber/ngx_http_google_filter_module#106]
After installing this module, sometimes the below entry appears in the error log for nginx [sensitive information is hidden].  

2016/05/04 11:43:53 [alert] 14401#14401: _4908 http request count is zero while sending to client, client: x.x.x.x, server: hostname.com, request: "POST /url?_***\* HTTP/2.0", upstream: "https://upstream.server.address:443/url?*****", host: "hostname.com"  

Is it a normal situation? What does it mean?

Thanks.

**Comment by cuber** [comment]
Upgrade your nginx, this is a bug
see the change log of nginx 1.11.2

**Comment by GwynethLlewelyn** [comment]
Huh. I *have* upgraded it, long time after this issue was closed. And today it's popping up again. What's going on?
