### ISSUE TITLE
怎么获取google ip 呢？？

### ISSUE THREAD

**Issue by pankui** [cuber/ngx_http_google_filter_module#109]
根据您的这个命令：dig www.google.com @8.8.8.8 +short   只获取一个ip.

然后使用网友说的： nslookup -q=TXT _netblocks.google.com 8.8.8.8

获取Ip段，但是不知道哪个是指向google.com 的？

**Comment by vinkenvvt** [comment]
用这个查下试试 嘻嘻
https://cachecheck.opendns.com

**Comment by pankui** [comment]
@vinkenvvt   可以查询到，但是根据 博主的方法来，还是有验证码。而且验证码不显示的。。

**Comment by vinkenvvt** [comment]
@pankui 我也遇到了... 貌似是谷歌的问题, 无解

**Comment by vinkenvvt** [comment]
@pankui 试一下这个... 我的现在恢复了
upstream www.google.com {
  least_conn;
  server 216.58.197.128:443 fail_timeout=2s max_fails=1;
  server 216.58.197.129:443 fail_timeout=2s max_fails=1;
  server 216.58.197.130:443 fail_timeout=2s max_fails=1;
  server 216.58.197.160:443 fail_timeout=2s max_fails=1;
  server 216.58.197.161:443 fail_timeout=2s max_fails=1;
  server 216.58.197.162:443 fail_timeout=2s max_fails=1;
  server 216.58.197.192:443 fail_timeout=2s max_fails=1;
  server 216.58.197.193:443 fail_timeout=2s max_fails=1;
  server 216.58.197.194:443 fail_timeout=2s max_fails=1;
  server 216.58.197.195:443 fail_timeout=2s max_fails=1;
  server 216.58.197.224:443 fail_timeout=2s max_fails=1;
  server 216.58.197.225:443 fail_timeout=2s max_fails=1;
  server 216.58.197.226:443 fail_timeout=2s max_fails=1;
  server 216.58.200.160:443 fail_timeout=2s max_fails=1;
  server 216.58.200.161:443 fail_timeout=2s max_fails=1;
  server 216.58.200.162:443 fail_timeout=2s max_fails=1;
  server 216.58.200.163:443 fail_timeout=2s max_fails=1;
  server 216.58.200.192:443 fail_timeout=2s max_fails=1;
  server 216.58.200.193:443 fail_timeout=2s max_fails=1;
  server 216.58.200.194:443 fail_timeout=2s max_fails=1;
  server 216.58.200.195:443 fail_timeout=2s max_fails=1;
  server 172.217.25.192:443 fail_timeout=2s max_fails=1;
  server 172.217.25.193:443 fail_timeout=2s max_fails=1;
  server 172.217.25.194:443 fail_timeout=2s max_fails=1;
  server 172.217.25.195:443 fail_timeout=2s max_fails=1;
  server 172.217.25.224:443 fail_timeout=2s max_fails=1;
  server 172.217.25.225:443 fail_timeout=2s max_fails=1;
  server 172.217.25.226:443 fail_timeout=2s max_fails=1;
  server 172.217.25.255:443 fail_timeout=2s max_fails=1;
}

**Comment by cuber** [comment]
可以看下这个项目 https://github.com/lennylxx/ipv6-hosts
