### ISSUE TITLE
用最简安装后一直显示Welcome to nginx!

### ISSUE THREAD

**Issue by YZBoo** [cuber/ngx_http_google_filter_module#120]
用最简安装后一直显示Welcome to nginx!
请问最简安装的话 nginx的配置文件在哪里？

**Comment by zhangmikoto** [comment]
/etc/nginx/nginx.conf

**Comment by Renlong-Yin** [comment]
也可直接 `vim /opt/nginx-1.7.8/conf/nginx.conf` 来修改配置文件。
