### ISSUE TITLE
[zmirror] 新一代通用镜像反代, 支持Google/维基/Gmail/Youtube/Twitter/Facebook/Instagram/more

### ISSUE THREAD

**Issue by aploium** [cuber/ngx_http_google_filter_module#122]
## Repo
本体: https://github.com/aploium/zmirror
一键部署脚本: https://github.com/aploium/zmirror-onekey
使用Python编写
一开始我也用了很久cuber大佬的这个, 后来这个停止更新了, 也只支持google, 就自己写了一个.

## Demo
* **Google**  
    * *网页搜索*   https://g.zmirrordemo.com  
   　PC端搜索结果页中的跳转已经自动移除  
   　无缝整合维基, 结果中的维基链接可以正常点开
    * *Scholar*   https://g.zmirrordemo.com/scholar  
    * *Image*   https://g.zmirrordemo.com/imghp  
    * *Gmail*   https://g.zmirrordemo.com/gmail  (请务必选择"使用基本HTML"版本)  

* **中文维基**  
    * *(PC & Mobile)*  https://g.zmirrordemo.com/wiki  

* **Youtube**  
    * *PC Only*  https://ytb-pc.zmirrordemo.com  
    * *Mobile Only* https://ytb-mobile.zmirrordemo.com  
    　　Youtube Mobile 不支持iOS
* **Twitter**
    * *PC Only*  https://t-pc.zmirrordemo.com  
    * *Mobile Only*  https://t-mobile.zmirrordemo.com
* **Instagram**
    * *PC & Mobile*  https://in.zmirrordemo.com  
* **Facebook**
    * *PC Only*  https://fb.zmirrordemo.com  
    　　绝大部分功能可用, 但是不完整  

## 更多配置文件
除了给出demo的以外,  zmirror同时还自带以下镜像的配置文件:
archive.org/duckduckgo/dropbox/Tumblr
Economist(经济学人)/thepiratebay(海盗湾)
详见 [zmirror自带配置文件详情](https://github.com/aploium/zmirror/blob/master/more_configs/readme.md)

## Screenshot
![zmirror-screenshot-youtube-mirror--1080P](https://github.com/aploium/zmirror/raw/wiki-pages/img/screenshot-youtube-1080p.jpg)  
 
### 最后
**欢迎贡献代码和赏星** ❤️  

本体: https://github.com/aploium/zmirror
一键部署脚本: https://github.com/aploium/zmirror-onekey

**Comment by lixingcong** [comment]
这个py项目好大啊。。。

**Comment by AlphaBrock** [comment]
非常棒，支持一个
