### ISSUE TITLE
./configure: error: C compiler cc is not found

### ISSUE THREAD

**Issue by 23330** [cuber/ngx_http_google_filter_module#128]
ubuntu 14.04 x86_64 重装后按顺序执行命令到# 设置编译选项
时 仍旧提示这个 
checking for OS
 `+` Linux 2.6.32-042stab120.6 x86_64
checking for C compiler ... not found

./configure: error: C compiler `cc` is not found

**Comment by lixingcong** [comment]
apt-get install build-essential

**Comment by 23330** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package build-essential

**Comment by 23330** [comment]
我尝试设置环境变量declare -x gcc="CC" 现在错误变成了./configure: error: C compiler `gcc` is not found

**Comment by WangQiliang** [comment]
apt-get update
apt-get install build-essential
