### ISSUE TITLE
wiki里ubuntu install一段命令有问题

### ISSUE THREAD

**Issue by fudanglp** [cuber/ngx_http_google_filter_module#131]
(1) zlib1.2.8 链接失效
建议改为1.2.11
(2) 第二行./configure 的所有参数前面都多了一个.

修改之后：
apt-get -y install build-essential git gcc g++ make && mkdir wen.lu && cd wen.lu && git clone https://github.com/cuber/ngx_http_google_filter_module && git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_module && wget "http://nginx.org/download/nginx-1.10.2.tar.gz" && tar xzvf nginx-1.10.2.tar.gz && wget "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz" && tar xzvf pcre-8.39.tar.gz && wget "http://zlib.net/zlib-1.2.11.tar.gz" && tar xzvf zlib-1.2.11.tar.gz &&  wget "https://www.openssl.org/source/openssl-1.1.0c.tar.gz" && tar xzvf openssl-1.1.0c.tar.gz && cd nginx-1.10.2

./configure --prefix=/opt/nginx-1.10.2 --with-pcre=../pcre-8.39 --with-openssl=../openssl-1.1.0c --with-zlib=../zlib-1.2.11 --with-http_ssl_module --add-module=../ngx_http_google_filter_module --add-module=../ngx_http_substitutions_filter_module && make

make install

**Comment by xuwenping123** [comment]
楼上基于该版本编译安装成功了么？
我的编译报错：
objs/Makefile:1277: recipe for target 'install' failed
1277行内容如下：
test -d '$(DESTDIR)/usr/soft/nginx/nginx-1.10.2' || mkdir -p '$(DES     TDIR)/usr/soft/nginx/nginx-1.10.2'
怎么回事呢？

**Comment by rongxm** [comment]
这个.不是多余的啊，没点怎么编译啊。我zlib1.2.11编译成功了，所有步骤都成功了，就是按照最简单配置不起作用，看不到google.
