### ISSUE TITLE
大大能弄个disqus评论的来不？

### ISSUE THREAD

**Issue by panxw** [cuber/ngx_http_google_filter_module#132]
国内评论框基本不能用，如果有一个可以反向代理disqus的就好了。

**Comment by fanhaozzu** [comment]
用畅言吧

**Comment by cn-jiangfei** [comment]
> 国内评论框基本不能用，如果有一个可以反向代理disqus的就好了。

用HashOver吧，目前我遇到的最好的评论系统，没有之一！
https://www.jiangfei.net/jianzhan/1142.html
