### ISSUE TITLE
反代google可以了，但google scholar就显示 sorry.....

### ISSUE THREAD

**Issue by rongxm** [cuber/ngx_http_google_filter_module#141]
问题是我同一个ip服务器用Shadowsocks连接，可以正常访问google scholar啊，有没有人懂咋整？有可能SS走的IPv6，反代只走ipv4，而ipv4地址被封了？

**Comment by mmccto1500** [comment]
@rongxm 厉害了，起码可以把Google反代出来。。。我的还在nginx欢迎您，不知道upstream模块怎么写

**Comment by cuber** [comment]
一些大的vps整个段可能都会被scholar ban了，例如 do或者vultr，建议换个小众vps
