### ISSUE TITLE
能不能一台服务器同时代理谷歌和谷歌学术

### ISSUE THREAD

**Issue by joydamn** [cuber/ngx_http_google_filter_module#143]
使用nginx的反向代理能不能在一台vps上同时代理谷歌和谷歌学术呢，当然，server分别是
`www.example.com`和`scholar.example.com`，当然，最好都支持https访问，如果可以的话，该如何配置？另外，域名解析该如何设置呢，www域名和scholar子域名跳转到同一个vps的ip地址可以吗。

**Comment by cuber** [comment]
建议不要多开子域，这样一封封俩，得不偿失
