### ISSUE TITLE
图片搜索的延迟现象

### ISSUE THREAD

**Issue by wszf5560** [cuber/ngx_http_google_filter_module#16]
首先多谢cuber提供好工具。
用了这个模块后，进行g图片搜索时，最初只能刷出来一部分。
过了大约半分钟到一分钟，向下翻动时能刷新出许多行。
然后又停顿了，继续等一阵之后才能继续缓冲出来。
http中 gzip和proxy，chache关闭与否都有没有好的效果，
请问这可能是哪出的问题？

**Comment by cuber** [comment]
谢谢反馈，似乎这个问题的确存在，我抽空尽快 fix

**Comment by wszf5560** [comment]
多谢你的关注。
出现缓存慢或者刷新慢的问题还真不一定是模块问题，因为我用xie.lu时，效果很好的。
我用美帝的机房，但通过其它代理方式图片秒开。
scholar已经测试完成，可以正常连接了。
Many thanks.

**Comment by cuber** [comment]
试一下最新的 dev 分支，看下问题是否还存在

**Comment by wszf5560** [comment]
好的，我现在就进行测试，辛苦了！:)

**Comment by wszf5560** [comment]
Cube 你好，
刚才测试完，*scholar问题已经完美解决了*。 图片缓冲有显著提升，一次可以刷出来很多。现在不算快，我觉得可能是高峰期网速问题。
不知您能否给我发一份简单的nginx.conf配置，我这里参数貌似太多了。一会我去掉一些参数，继续优化一下。
然后再给你反馈信息。
谢谢！

祝 好！


2015-01-14 21:43 GMT+08:00 fir Befamous <wszf5560@gmail.com>:

> 好的，我现在就进行测试，辛苦了！:)
>

**Comment by wszf5560** [comment]
搜索体验良好，多谢cuber:)
