### ISSUE TITLE
发现简洁安装教程里面没有安装可以使用HTTPS证书的conf么？还是我哪部分搞错了？

### ISSUE THREAD

**Issue by SharkIng** [cuber/ngx_http_google_filter_module#18]
按照简洁安装之后发现SSL证书不能下，在.conf里面使用ssl on; 后启动nginx报错？
检查了下configuration的语句有安装OpenSSL但是好像没有安装nginx的ssl模块，是这样么？个人对服务器还是不很精通不确定是不是判断准确了

**Comment by wszf5560** [comment]
config时加上 --with-http_ssl_module 这个试试看。

**Comment by SharkIng** [comment]
嗯的确是那句的问题，重新config就好了
但是觉得是不是应该把这个加在教程里免费别人不知道
