### ISSUE TITLE
试了下频繁操作还是会出验证码

### ISSUE THREAD

**Issue by leecade** [cuber/ngx_http_google_filter_module#2]
这个问题估计只有多出口 ip 才行

**Comment by helegehe** [comment]
你配置好了这个模块能用吗？为什么我配置好以后Nginx返回502 Bad Gateway

**Comment by helegehe** [comment]
问题解决了吗  我这也出验证码 而且浏览器这边还看不到图片

**Comment by cuber** [comment]
@helegehe 
更新到最新版，并且清除浏览器 cookie, 缓存等试试看

**Comment by cdroad** [comment]
我这边完全大丈夫。

**Comment by k1995** [comment]
请问这个问题解决了么？

**Comment by helegehe** [comment]
解决了，没有做什么改动，重启了几次，后来没有出问题了。谢谢




------------------ 原始邮件 ------------------
发件人: "k1995";<notifications@github.com>;
发送时间: 2015年10月14日(星期三) 下午2:49
收件人: "cuber/ngx_http_google_filter_module"<ngx_http_google_filter_module@noreply.github.com>; 
抄送: "诺风"<1055563133@qq.com>; 
主题: Re: [ngx_http_google_filter_module] 试了下频繁操作还是会出验证码 (#2)




请问这个问题解决了么？

**Comment by leecade** [comment]
closes. 我没有问题了
