### ISSUE TITLE
不能用啊

### ISSUE THREAD

**Issue by helegehe** [cuber/ngx_http_google_filter_module#21]
设置好以后  服务器返回504 badgetway。

**Comment by cuber** [comment]
方便贴下配置么

**Comment by helegehe** [comment]
你好Cube ：
    谢谢你给我回邮件。
    那个问题解决了  没有设置proxy_resolver   。
    但是现在有一个新问题，配置好nginx以后，在浏览器里访问报错，错误信息如下：
  
   此页面不能正确地重定向
Firefox 检测到该服务器正在将此地址的请求循环重定向。‍


对服务器进行抓包发现，首先nginx会像8.8.8.8发送请求解析www.google.com，然后8.8.8.8返回一个172的谷歌ip，接着nginx想这个ip发送get请求，谷歌服务器返回304，地址是http:\\www.google.com，然后又进入请求http:\\www.google.com，域名解析，‍
返回304死循环当中。。




   配置如下





------------------ 原始邮件 ------------------
发件人: "Cube";<notifications@github.com>;
发送时间: 2015年1月26日(星期一) 上午9:33
收件人: "cuber/ngx_http_google_filter_module"<ngx_http_google_filter_module@noreply.github.com>; 
抄送: "诺风"<1055563133@qq.com>; 
主题: Re: [ngx_http_google_filter_module] 不能用啊 (#21)




方便贴下配置么

**Comment by cuber** [comment]
你清除一下浏览器 cookie 再试一下

**Comment by helegehe** [comment]
清理了 还是不行 浏览器依然显示：此网页包含重定向循环 nginx配置里就写了三条，监听8000 端口 ，配置域名服务器8.8.8.8，然后 google  on。

**Comment by helegehe** [comment]
请教一下  用你这个模块和   直接配置   nginx给google做反向代理  有差别吗？？

**Comment by helegehe** [comment]
hello:
       我这边弹验证码，并且浏览器中还不显示，请问有解决办法吗？
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Cube";<notifications@github.com>;
 发送时间: 2015年1月26日(星期一) 晚上7:26
 收件人: "cuber/ngx_http_google_filter_module"<ngx_http_google_filter_module@noreply.github.com>; 
 抄送: "诺风"<1055563133@qq.com>; 
 主题: Re: [ngx_http_google_filter_module] 不能用啊 (#21)

 

 
Closed #21 via 3785965.
