### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by eallion** [cuber/ngx_http_google_filter_module#23]
-bash: --add-module=../ngx_http_substitutions_filter_module: No such file or directory

**Comment by eallion** [comment]
#
# 设置编译选项
#
./configure \
  --prefix=/opt/nginx-1.7.8 \
  --with-pcre=../pcre-8.36 \
  --with-openssl=../openssl-1.0.1j \
  --with-zlib=../zlib-1.2.8 \
  --add-module=../ngx_http_google_filter_module
  --add-module=../ngx_http_substitutions_filter_module


是不是差个“\”

**Comment by cuber** [comment]
sorry，的确少一个反斜杠 谢谢指正
