### ISSUE TITLE
能不能多分享几个GoogleIP

### ISSUE THREAD

**Issue by oamzn** [cuber/ngx_http_google_filter_module#29]
upstream www.google.com {
	server 173.194.38.1:443;
	server 173.194.38.2:443;
	server 173.194.38.3:443;
	server 173.194.38.4:443;
	server 123.205.251.100;	
}
能不能多分享几个Google IP，不知道这样写80端口的IP是否可行。
此外我配置完成后手机端打不开，PC正常。
还有，我发现同一个问题搜索，搜到的结果g.wen.lu和我g.cniot.info搜索出的结果不同，请指教。

**Comment by dzhwinter** [comment]
这是因为google 根据你的点击先验做过预测了。



dzhwinter@gmail.com
 
发件人： oamzn
发送时间： 2015-04-03 18:54
收件人： cuber/ngx_http_google_filter_module
主题： [ngx_http_google_filter_module] 能不能多分享几个GoogleIP (#29)
upstream www.google.com {
server 173.194.38.1:443;
server 173.194.38.2:443;
server 173.194.38.3:443;
server 173.194.38.4:443;
server 123.205.251.100; 
}
能不能多分享几个Google IP，不知道这样写80端口的IP是否可行。
此外我配置完成后手机端打不开，PC正常。
还有，我发现同一个问题搜索，搜到的结果g.wen.lu和我g.cniot.info搜索出的结果不同，请指教。
