### ISSUE TITLE
Question: Does it verify upstream SSL certificates?

### ISSUE THREAD

**Issue by biergaizi** [cuber/ngx_http_google_filter_module#32]
Does the module verify the upstream connection to Google servers, provides protection from MITM attacks?

**Comment by cuber** [comment]
This module is using the native nginx `ngx_http_proxy_module` to make proxy requests, so the behavior of ssl verification depend on nginx itself.
There is an option `proxy_ssl_verify ` with nginx version >= 1.7.0, you can do some test on it and i will be happy to know the results.
Maybe this link http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_verify can help
