### ISSUE TITLE
清除Cookie以后首次访问会出现400错误

### ISSUE THREAD

**Issue by fprint** [cuber/ngx_http_google_filter_module#33]
非常感谢，我也试着弄了一个http://n54l.com。
有个小问题，就是第一次访问nginx会报400错误，然后我看返回的地址是
http://n54l.com/%00 
正常的话会返回
http://n54l.com/?gws_rd=ssl%00
不知道是哪里出问题了。

**Comment by cuber** [comment]
你试试在 terminal 
```bash
curl "n54l.com" -I -v
```
然后把nginx配置和返回结果贴一下
btw 
你可以试一下 `host`: `106.185.54.78 wen.lu` 试试看你那访问 `wen.lu` 是否也有这个问题

**Comment by fprint** [comment]
谢谢回复，因为这个问题，我昨天把https配置好了，然后就没问题了。另外，我访问问路是正常的。http://im.fprint.org 
我之前用的http

**Comment by fprint** [comment]
这个东东太给力了，我f q一大半时间在谷歌上。

**Comment by cuber** [comment]
谢谢反馈，我会多做一些 `http` 的测试。
很高兴这个模块能帮到你。
