### ISSUE TITLE
关于首次访问出现"400 bad request"错误

### ISSUE THREAD

**Issue by fprint** [cuber/ngx_http_google_filter_module#34]
还是我哈，清除cookie以后，首次访问网站，会出现"400 bad request"，我看到地址栏返回的结果是"http:://domain.name/%00，然而第二次以后访问都正常了。

我把nginx日志打开了，看到有这条。

2015/05/15 17:27:12 [info] 17257#0: *1 client sent invalid request while reading client request line, client: 113.87.235.183, server: localhost, request: "GET /%00 HTTP/1.1"

**Comment by fprint** [comment]
我分别用safari、chrome、ie，在清除所有cookie后访问，结果只有safari会这样，其他两个都可以正常访问。

**Comment by fprint** [comment]
据说firefox也出这个问题

**Comment by cuber** [comment]
谢谢反馈，我试试看
