### ISSUE TITLE
部分浏览器和访客反应重定位过多

### ISSUE THREAD

**Issue by loev139** [cuber/ngx_http_google_filter_module#39]
很奇怪，我配置都是正常的。我手机、电脑的chrome 正常，电脑safari也正常。但就是手机safari和电脑遨游浏览器不正常，老是说重定位太多。 另外，很多朋友也给我说打不开！   怎么解决呢？https://s.ets.cc/

**Comment by cuber** [comment]
我试了下配置语言为en的时候，的确有这个问题
```nginx
google_language 'en';
```
谢谢反馈，我尽快修复

**Comment by loev139** [comment]
我刚才也在琢磨，后来发现就是设置语言与服务器所在地语言不一样的话，就会多次重定向
