### ISSUE TITLE
failed: /root/ssl/g4w.me.crt

### ISSUE THREAD

**Issue by OuIChien** [cuber/ngx_http_google_filter_module#40]
nginx: [emerg] BIO_new_file("/root/ssl/g4w.me.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/root/ssl/g4w.me.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
按照您的操作步骤，在 nginx -t 时抛出上面的错误，是否要下载证书？在哪里下载？谢谢～

**Comment by cuber** [comment]
证书是需要花钱购买的
btw, 如果纯自用你可以 google 一下自签名证书
