### ISSUE TITLE
Help for nonprogrammer needed.

### ISSUE THREAD

**Issue by cdmask** [cuber/ngx_http_google_filter_module#44]
Can you guys make a tutorial for nonprogrammers to explain briefly how the project works and show us how  to use it(graphically)?
I think that would help more people access your project.
Thank you : )

**Comment by cuber** [comment]
Thanks for your proposal, there are many specific tutorials available.
Such as 
http://imtx.me/archives/1934.html 
http://ttt.tt/162/ 
http://story.limboshop.info/2015/06/17/free-search-project/
I will summarize and add them to the guide page, also attach some nonprogrammer diagrams. :-)

**Comment by cdmask** [comment]
Thanks~
