### ISSUE TITLE
centos 经常出现nginx错误  偶尔正常

### ISSUE THREAD

**Issue by wanglong167** [cuber/ngx_http_google_filter_module#45]
[alert] 22169#0: *15 socket() failed (97: Address family not supported by protocol) while connecting to upstream, client: 116.234.73.109, server: localhost, request: "GET /search?newwindow=1&site=&source=hp&q=%E6%9F%A5%E7%9C%8Bcentos+log&btnG=Google+%E6%90%9C%E7%B4%A2 HTTP/1.1", upstream: "https://[2404:6800:4005:80a::2004]:443/search?newwindow=1&site=&source=hp&q=%E6%9F%A5%E7%9C%8Bcentos+log&btnG=Google+%E6%90%9C%E7%B4%A2", host: "203.88.160.49", referrer: "http://203.88.160.49/"

**Comment by cuber** [comment]
大概意思就是 nginx 把域名解析成了 ipv6，而你的机器 disable 了 ipv6，所以造成了 Address family not supported by protocol

**Comment by cuber** [comment]
你可以 `resolver 8.8.8.8 ipv6=off;` 试一下看看有木有用

**Comment by wanglong167** [comment]
的确好了 谢谢 但是 图片搜索 http://203.88.160.49/imghp?hl=zh-CN&tab=wi 无法访问

**Comment by cuber** [comment]
谢谢反馈，单用 ip 的时候，的确有这个问题
