### ISSUE TITLE
建议做得再通俗易懂一些

### ISSUE THREAD

**Issue by ntgeralt** [cuber/ngx_http_google_filter_module#49]
我在香港拥有几台vps在cn2线路上。但我英文真的很差，我觉得大家都是中国人，做个中文版的福利一下像我这样有资源却没文化的人吧！相反国务院审查部的人可能英文水平很高，你把台阶抬高，拦住我们而不是拦他们.

**Comment by cuber** [comment]
https://github.com/cuber/ngx_http_google_filter_module/blob/master/README.zh-CN.md
有中文教程呀

**Comment by cuber** [comment]
Duang~
