### ISSUE TITLE
求阅读源码的建议

### ISSUE THREAD

**Issue by time-river** [cuber/ngx_http_google_filter_module#54]
我是C的初学者，刚刚接触nginx。
想阅读这个项目的源码，该从何入手呢？
需要了解些什么知识呢？

**Comment by cuber** [comment]
初学者建议先别从 nginx 开始看... 顿挫感会很强...
建议先多看看 c 实现的数据结构, 例如 map, list, hash_table, bitmap 等等, 然后再看看网络编程, 知道如何使用套接字, 深入了解异步编程模型, 然后再来看 nginx
btw, 最好再深入学会使用一个 ide, 例如 Xcode 或者 Eclipse
