### ISSUE TITLE
一个谷粉搜搜和g363这类网站非原版的谷歌镜像他们是怎么改变网站版面的呢？

### ISSUE THREAD

**Issue by sisiww** [cuber/ngx_http_google_filter_module#59]
谷粉搜搜和g363这类网站他们是谷歌镜像站还是调用谷歌的api的呢？然后网站版面全部都改变了。而且搜索的地址栏链接也发生了改变，这类网站得到的谷歌结果是镜像的吗？求实在原理

**Comment by k1995** [comment]
谷歌应该没有提供api吧。他们应该是谷歌获取数据后在进行过滤修改，参考【whats搜索】

**Comment by sisiww** [comment]
不会是用ngx_http_substitutions_filter_module这个模块过滤修改的吗？过滤界面太复杂代码过多了，不可能是用ngx_http_substitutions_filter_module这个模块过滤的吗？whatsoo这个是你的？

**Comment by k1995** [comment]
嘿嘿(*^__^*) 。这几天还在研究nginx呢，C语言嘛确实比较复杂。whats搜素是用php的curl获取数据，然后修改的比较简单。

**Comment by sisiww** [comment]
直接用php的curl获取数据，那相当于搜索结果是提取的，不是直接通过代理服务器请求得出来的结果。

**Comment by sisiww** [comment]
亲，弱弱的问下需要哪些nginx的依赖库呢还有要哪些扩展呢？

**Comment by meilele** [comment]
GitLab

**Comment by meilele** [comment]
GitLab
