### ISSUE TITLE
$google_host/! 后面是不是可以加上任何地址，可以代理任何网站呢？

### ISSUE THREAD

**Issue by vinken** [cuber/ngx_http_google_filter_module#60]
效果如https://gg.wen.lu/!dynm.waem.org/me.php 或者 https://gg.wen.lu/!twitter.com
求问有办法解决这个问题么
谢谢啦! :P

**Comment by cuber** [comment]
理论来说是的。
但是拿 twitter 来说， 现在的网页技术，都不会把资源放在 twitter.com 里面一次全部加载完，而且是先载入一个框架，然后异步载入资源，这些资源的 proxy 替换是十分复杂和麻烦的，所以实际来说，是行不通的

**Comment by vinken** [comment]
谢谢你 :)

**Comment by cuber** [comment]
:-)
