### ISSUE TITLE
upstream "google" 

### ISSUE THREAD

**Issue by fchypzero** [cuber/ngx_http_google_filter_module#61]
Stoping nginx... nginx: [emerg] duplicate upstream "google" in /usr/local/nginx/conf/vhost/gg.0l0.pw.conf:9
 failed. Use force-quit
----以上是错误----
在设置了upstream之后，重启nginx就会出现这样的错误，求解。

----------------------

upstream google {
server 74.125.200.101:443;
server 74.125.200.100:443;
server 74.125.200.139:443;
server 74.125.200.113:443;
server 74.125.200.138:443;   
}

server {
    listen 80;
    server_name g.xxx.pw;
    return 301 https://g.xxx.pw$request_uri;
}

server {
    listen 443 ssl;
    server_name g.xxx.pw;
 
    ssl on;
    ssl_certificate /hx.crt;
    ssl_certificate_key /hxe.key;
    resolver 8.8.8.8;

    location / {
        google on;
        google_scholar on;
        google_language "zh-TW"; 
    }
}

**Comment by cuber** [comment]
upstream google 改成 upstream www.google.com

**Comment by fchypzero** [comment]
搞定~话说有没有考虑加入缓存？

**Comment by cuber** [comment]
google 本身已经够快了，io 密集型 cpu 不是瓶颈，无需做缓存

**Comment by Showfom** [comment]
直接用 nginx 自带缓存即可 一般我设置缓存半小时

On Thursday, 22 October 2015, fchypzero <notifications@github.com> wrote:

> 搞定~话说有没有考虑加入缓存？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/61#issuecomment-150201779>
> .
>


-- 
Best Regards,
@Showfom

**Comment by cuber** [comment]
:-)
