### ISSUE TITLE
可否提供googlevideo.com的反代服务

### ISSUE THREAD

**Issue by wdfsinap** [cuber/ngx_http_google_filter_module#62]
youtube下的视频是用googlevideo.com，反代老是不成功，请问你能给提供这个服务吗。谢谢

**Comment by Showfom** [comment]
那个不科学，而且反代了速度更慢。

2015-10-25 18:50 GMT+08:00 wdfsinap <notifications@github.com>:

> youtube下的视频是用googlevideo.com，反代老是不成功，请问你能给提供这个服务吗。谢谢
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/62>.
>



-- 
Best Regards,
@Showfom

**Comment by wdfsinap** [comment]
为什么不科学。我解析到的youtube视频确实是googlevideo.com的子域名提供的。速度慢不是大问题。可以用好点的服务器。能帮解决下吗

**Comment by wdfsinap** [comment]
我的配置如下
server {
listen 80;
server_name ~^(.+).mydomain.com$;
location / {
resolver 8.8.8.8;

 proxy_pass https://$1.googlevideo.com;
 proxy_set_header referer https://$1.googlevideo.com;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header Host $1.googlevideo.com;
 proxy_redirect off;
 proxy_set_header User-Agent $http_user_agent;
}
}
不过老是不成功，是不是因为没有用SSL被block了？

**Comment by Showfom** [comment]
googlevideo.com 的子域名无法统计，太多了。再好的服务器速度也慢，因为限速的。

On Sun, Oct 25, 2015 at 7:12 PM, wdfsinap <notifications@github.com> wrote:

> 我的配置如下
> server {
> listen 80;
> server_name ~^(.+).mydomain.com$;
> location / {
> resolver 8.8.8.8;
>
> proxy_pass https://$1.googlevideo.com;
> proxy_set_header referer https://$1.googlevideo.com;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header Host $1.googlevideo.com;
> proxy_redirect off;
> proxy_set_header User-Agent $http_user_agent;
> }
> }
> 不过老是不成功，是不是因为没有用SSL被block了？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/62#issuecomment-150912625>
> .
>



-- 
Best Regards,
@Showfom

**Comment by wdfsinap** [comment]
你看我的配置，我用了泛域名反代，刚开始反代成功了。过了两天就老跳转会googlevideo.com。速度不是大问题。我自己用的。所以麻烦给解决下。

**Comment by Showfom** [comment]
你也用 443 啊

2015-10-25 19:21 GMT+08:00 wdfsinap <notifications@github.com>:

> 你看我的配置，我用了泛域名反代，刚开始反代成功了。过了两天就老跳转会googlevideo.com。速度不是大问题。我自己用的。所以麻烦给解决下。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/62#issuecomment-150912974>
> .
>



-- 
Best Regards,
@Showfom

**Comment by nxtreaming** [comment]
2015-10-25 19:21 GMT+08:00 wdfsinap <notifications@github.com>:

> 你看我的配置，我用了泛域名反代，刚开始反代成功了。过了两天就老跳转会googlevideo.com。速度不是大问题。我自己用的。所以麻烦给解决下
>

自己用根本没有必要反代啊！

直接做正向代理多简单？

-- 
Founder of http://coogle.io

**Comment by cuber** [comment]
Bang ~
