### ISSUE TITLE
需要在同级目录下安装zlib

### ISSUE THREAD

**Issue by myandrew** [cuber/ngx_http_google_filter_module#66]
ubuntu 14.04 x64
make 提示错误 找不到zlib.h
用apt-get install zlib1g-dev之后make会提示cd错误 找不到zlib-1.2.8这个目录
后来自己在nginx同级目录下载之后才能编译通过
wget http://zlib.net/zlib-1.2.8.tar.gz
tar zxvf zlib-1.2.8.tar.gz
cd nginx-1.7.8
make

**Comment by cuber** [comment]
参考从发行版迁移这个部分，我在 ubuntu 14.04 测试过，不应该需要下载 zlib 源码才对

**Comment by cuber** [comment]
Bang ~
