### ISSUE TITLE
could not found pcre-8.36

### ISSUE THREAD

**Issue by hakale** [cuber/ngx_http_google_filter_module#71]
wget "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.gz" filed
it has changed to pcre-8.37
and ./configure \ should also change to   --with-pcre=../pcre-8.37 \

**Comment by xinyue** [comment]
wget "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.gz"

**Comment by hakale** [comment]
thanks,it's same as 8.37
