### ISSUE TITLE
Maximum redirects followed

### ISSUE THREAD

**Issue by registe** [cuber/ngx_http_google_filter_module#74]
→ ~ $ curl -IL https://www.noeg.net
HTTP/1.1 302 Found
Date: Tue, 15 Dec 2015 03:49:36 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Location: https://www.noeg.net/
Cache-Control: private
P3P: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: NID=74=NLXmTxYIcFbU1EYMnWTpMZ4Ueym-KgOTShoGW3IqLk_eCoyhOJ4btQ9-vo3ny5_ij-a4QGG4q0gttr3jVNL3cM77UYU-pMrpxBLM1mIFMZ3q48wGq6pY2EFGNtfuRLEw; expires=Wed, 15-Jun-2016 03:49:37 GMT; path=/; domain=.www.noeg.net
Alternate-Protocol: 443:quic,p=0
Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25"
Server: www.noeg.net/0.1.9
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

........
........
........

HTTP/1.1 302 Found
Date: Tue, 15 Dec 2015 03:50:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Location: https://www.noeg.net/
Cache-Control: private
P3P: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: NID=74=uJUt-s0j30LZAbjrHTWNWtlkq-ZjAFX6EGPwUbv02MoWXxFxayz6A9TowmJ_5OzHTolAE6wlM6Q-TZXDk5nkhMa9kbhn6rYxBpur1RA9_r04k8Lvq7WF2iZ55uKr9Juo; expires=Wed, 15-Jun-2016 03:50:06 GMT; path=/; domain=.www.noeg.net
Alternate-Protocol: 443:quic,p=0
Alt-Svc: quic="www.google.com:443"; ma=600; v="30,29,28,27,26,25"
Server: www.noeg.net/0.1.9
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff

curl: (47) Maximum (50) redirects followed

**Comment by registe** [comment]
[test@noeg ~]$ cat /etc/nginx/conf.d/noeg.net.conf 
upstream www.google.com {
	server ip:443;
	......
}

server {
	listen 443 ssl spdy default;
	server_name noeg.net www.noeg.net;

	ssl on;
	ssl_ciphers "AES128+EECDH:AES128+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	ssl_session_cache shared:SSL:10m;
	ssl_session_tickets off;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_dhparam /etc/nginx/conf.d/noeg.net.pem;
	ssl_certificate /etc/nginx/conf.d/noeg.net.crt;
	ssl_certificate_key /etc/nginx/conf.d/noeg.net.key;

	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
	add_header X-Frame-Options SAMEORIGIN;
	add_header X-Content-Type-Options nosniff;

	access_log /var/log/nginx/noeg.net.access.log;
	error_log /var/log/nginx/noeg.net.error.log;

	keepalive_timeout 60;
	resolver 8.8.8.8;

	location / {
		google on;
		google_scholar on;
		#google_language en;
		#subs_filter '_\.ua\("rwt",function\(\)\{[^\}]*\}\);' '' igr;
	}

}

server {
	listen 80;
	server_name www.noeg.net;
	rewrite ^(.*) https://www.noeg.net$1 permanent;
}

**Comment by cuber** [comment]
Oops, you should try with your browser, the curl cli command may not add the cookie to the next redirection request

**Comment by registe** [comment]
@cuber I try safari, google chrome and mozilla firefox, and I get the same results.

with curl:

```
HTTP/1.1 302 Found
Date: Tue, 15 Dec 2015 04:13:45 GMT
...
Set-Cookie: NID=74=qZM0T3xZelFiE2qunXRc_R7j5zyOeupGc_I7u0gkmGFrsva2zsjCHtYyralGMAYalr0SM__EtlfYGY6TnifYs0LxAKGPr3FnKdKWebX6piaPTMIz-REbon6PT-c24inr; expires=Wed, 15-Jun-2016 04:13:46 GMT; path=/; domain=.www.noeg.net
...

HTTP/1.1 302 Found
Date: Tue, 15 Dec 2015 04:13:45 GMT
...
Set-Cookie: NID=74=PkDAjm5hVATvB3o0Ya4oJc93Myx0PFa0Ct1t3cjpVDS_4fXfC2W0EnJO_XZs9LApkisqxJljV8jANsqg5XG-zf2zC11TgXnQD4_pq-_EUjzXnj3yklKKJgFFpUZlzECf; expires=Wed, 15-Jun-2016 04:13:46 GMT; path=/; domain=.www.noeg.net
...

HTTP/1.1 302 Found
Date: Tue, 15 Dec 2015 04:13:46 GMT
...
Set-Cookie: NID=74=tMcRl3DJ4tv_tpTqosCt-vqhHa6PBh6HZcFK-owXzC8U1_2Z2mSQb0PNU1hs3rxuwLDdHyq-AANMNiSLwd9hitd9ELEsc4mvN4ttCKC8P2W5pd1CgPzQPrH71EnwCepj; expires=Wed, 15-Jun-2016 04:13:46 GMT; path=/; domain=.www.noeg.net
...

...
...
```

**Comment by complexly** [comment]
Similar problem since this morning. When opening my own google page with Chrome, it shows "Redirect Loop Problem" and "ERR_TOO_MANY_REDIRECTS". Clearing the cookies in Chrome has no effects. However, IE can open this page properly...

I used an older version of the config, will update to the nearest version (3 days ago) solve this problem?

**Comment by cuber** [comment]
Maybe google has updated the cookie syntax, `g1.wen.lu` got the same problem too. 
I will fix this as soon as possible.

**Comment by cuber** [comment]
@registe @complexly 
Could you try the latest dev branch to test if this problem has gone?

**Comment by registe** [comment]
@cuber 
the latest commits seems have solved the problem, thanks

**Comment by loev139** [comment]
How did you update to latest version? should I recompile Nginx and reload modules?

**Comment by cuber** [comment]
@loev139 you need switch to dev branch and recompile nginx

**Comment by chenbaiwan** [comment]
not work

**Comment by chenbaiwan** [comment]
sorry, I forget “cp -rf objs/nginx /usr/sbin/nginx”

the latest commits seems have solved the problem, thanks

**Comment by mhohai** [comment]
thanks
