### ISSUE TITLE
此网页包含重定向循环

### ISSUE THREAD

**Issue by weaming** [cuber/ngx_http_google_filter_module#78]
此网页包含重定向循环

ERR_TOO_MANY_REDIRECTS

**Comment by princecauchy** [comment]
我也遇到了这个问题。不知道是不是google改版了。

**Comment by weaming** [comment]
@princecauchy 很奇怪啊，之前能用的，难道我用了supervisor来监控nginx就不行了？

**Comment by wanglong167** [comment]
The document has moved 我也遇到了

**Comment by cuber** [comment]
更新到最新版本的代码试一下，之前 google 的确改版了 #74 应该和你们提的问题一样

**Comment by weaming** [comment]
@cuber 怎么更新，有教程吗

**Comment by princecauchy** [comment]
@weaming 直接重新编译安装一遍就ok了。

**Comment by weaming** [comment]
...晚上折腾

**Comment by asasuou** [comment]
git pull更新后
重新编译一下Nginx就可以了。

**Comment by weaming** [comment]
@更新后，编译，OK
我的脚本记录：https://github.com/weaming/gfw/blob/master/google%E4%BB%A3%E7%90%86.md
