### ISSUE TITLE
循环重定向

### ISSUE THREAD

**Issue by out0fmemory** [cuber/ngx_http_google_filter_module#79]
试了好几个版本的filter_module，全是循环重定向，上星期还是正常的，应该是谷歌改了什么东西

**Comment by cuber** [comment]
master 分支的最新版本就应该 ok，你从新编译下 nginx，编译完记得重启 nginx

**Comment by out0fmemory** [comment]
有点奇怪，我重新编译了master，nginx 1.8.0，还是不行，是不是跟我设置的upstream里的google地址有关？

**Comment by out0fmemory** [comment]
现在的配置
location / {
			#缓存
			#proxy_cache one;
			#proxy_cache_valid  200 302  1h;
			#proxy_cache_valid  404      1m;
            google on;
			google_scholar on;
			google_language zh-CN;
			google_ssl_off "www.google.com";
        }
upstream www.google.com {
	server 216.58.216.3 max_fails=3;
	#server 216.58.217.200 max_fails=3;
	#server 216.58.217.160 max_fails=3;
	#server 216.58.219.46 max_fails=3;
	#server 216.58.219.47 max_fails=3;
	#server 216.58.219.49 max_fails=3;
	#server 216.58.219.50 max_fails=3;
	#server 216.58.219.51 max_fails=3;
	#server 216.58.219.52 max_fails=3;
	#server 216.58.219.53 max_fails=3;
	#server 216.58.219.54 max_fails=3;
	#server 216.58.219.55 max_fails=3;
	#server 216.58.219.56 max_fails=3;
	#server 216.58.219.57 max_fails=3;
	#server 216.58.219.58 max_fails=3;
	#server 216.58.219.59 max_fails=3;
	#server 216.58.219.60 max_fails=3;
	#server 216.58.219.61 max_fails=3;
}

**Comment by cuber** [comment]
```
# 如下部分注释掉
# google_ssl_off "www.google.com"; 
# upstream { ... }
```
这个 `google_ssl_off` 选项是做二次转发用的，正常用不需要开启
`upstream` 这个如果流量不大，也建议关闭

**Comment by out0fmemory** [comment]
@cuber 多谢，问题已经解决了。另外有个建议，我们是不是可以再抽象完善一下搞成一个全网址的代理

**Comment by cuber** [comment]
@out0fmemory 全网址指的是？

**Comment by out0fmemory** [comment]
@cuber 比如可以代理谷歌，也可以代理wiki等等被墙的网站

**Comment by cuber** [comment]
@out0fmemory 每个网站的 rule 规则都不同，通用很难。
