### ISSUE TITLE
好像Google更改了什么东西，现在scholar没法反代了？

### ISSUE THREAD

**Issue by goxofy** [cuber/ngx_http_google_filter_module#81]

**Comment by cuber** [comment]
请更新到最新 master 分支

**Comment by shirakun** [comment]
表示这个分支是我随便克隆的，请去官方分支找，我自己没用过这个模块，我用的就是普通的反代，我现在一切正常
https://google.shirakun.cc/

**Comment by goxofy** [comment]
@cuber 我是昨晚clone了最新的分支，编译之后Google主页的重定向问题解决了，但是scholar还是有问题  https://letsgg.tk

**Comment by cuber** [comment]
把浏览器cookie清掉试试看
https://g1.wen.lu/scholar
学术能正常用

2016年1月7日星期四，TinK <notifications@github.com> 写道：

> @cuber <https://github.com/cuber>
> 我是昨晚clone了最新的分支，编译之后Google主页的重定向问题解决了，但是scholar还是有问题 https://letsgg.tk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/81#issuecomment-169911436>
> .
>


-- 

☺ HouRay

**Comment by mikelei8291** [comment]
我也发现了同样的问题，经测试，已确定原因如下：
当 `google_language` 的值为 `zh-CN` 以外的值时，Google Scholar会被无限302重定向，重定向过多浏览器自动中止连接。
当 `google_language` 的值为 `zh-CN` 或者未设置此项 (即默认打开Google简体中文) 时，Google Scholar可以被正常反代。作者 @cuber 的 wen.lu 就是这种情况

另外， @shirakun 你虽然设置了 `google_language "ja"` ，且可以打开Google Scholar，是因为你直接用301跳转了 scholar.google.com ，根本不是反向代理的结果。

**Comment by cuber** [comment]
谢谢反馈，我看下

在 2016年3月24日 上午2:24，Mike Lei <notifications@github.com>写道：

> 我也发现了同样的问题，经测试，已确定原因如下：
> 当 google_language 的值为 zh-CN 以外的值时，Google Scholar会被无限302重定向，重定向过多浏览器自动中止连接。
> 当 google_language 的值为 zh-CN 或者未设置此项 (即默认打开Google简体中文) 时，Google
> Scholar可以被正常反代。作者 @cuber <https://github.com/cuber> 的 wen.lu 就是这种情况
>
> 另外， @shirakun <https://github.com/shirakun> 你虽然设置了 google_language "ja"
> ，且可以打开Google Scholar，是因为你直接用301跳转了 scholar.google.com ，根本不是反向代理的结果。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cuber/ngx_http_google_filter_module/issues/81#issuecomment-200479903>
>



-- 

☺ HouRay
