### ISSUE TITLE
g1.wen.lu is blocked

### ISSUE THREAD

**Issue by bohanyang** [cuber/ngx_http_google_filter_module#90]
Please open a new subdomain...
Fuck GFW!

**Comment by weaming** [comment]
+1

**Comment by wangqiliang** [comment]
+1

**Comment by caibo2014** [comment]
+1

**Comment by imlinhanchao** [comment]
It's OK in Shenzhen.

**Comment by weaming** [comment]
@imlinhanchao Now is OK.

**Comment by cuber** [comment]
try g2.wen.lu instead :-)

**Comment by paperbag** [comment]
g2.wen.lu is blocked recently.  :(

**Comment by paperbag** [comment]
It seem that (*.)wen.lu is DNS poisoned. 
Fuck those people who work for GFW.
