### ISSUE TITLE
请问反代后出现的是旧版的Google是什么原因

### ISSUE THREAD

**Issue by suconghou** [cuber/ngx_http_google_filter_module#93]
![旧版Google](http://i13.tietuku.com/da48d5a79e74ed53.png)

**Comment by cuber** [comment]
google 会识别 user-agent 来判断展示样式，你是不是设置过这个东西

**Comment by suconghou** [comment]
已经好了,可能和网络运营商有关,在公司刷新几次就是新版了. 再问一下,此模块能不能使用 proxy_cache 和 proxy_ignore_headers  等一系列指令.

**Comment by cuber** [comment]
可以的
