### ISSUE TITLE
我把该工程部署到香港服务器上面对吗？

### ISSUE THREAD

**Issue by yangjiwen** [cuber/ngx_http_google_filter_module#97]
我按你的教程，部署到香港服务器上面，然后直接通过服务器ip:80访问,得到欢迎进入ngnix的页面，而没有跳转到google搜索界面啊？这个要绑定域名吗？我看你的ngnix 配置文件  
 location / {
  google on;
         }
 这个 location /  如果请求为（部署服务器ip/）那么匹配 就执行相应的 google on 代码？ 然后就能访问google服务了，我的理解对吗？

**Comment by wangofjian** [comment]
nginx.conf 里面设置了默认页面，一般是index.html ，建议在nginx.conf里面重新设置一个server，类似这样
    server {

        listen 8080;
        resolver 8.8.8.8;
        location / {
            google on;
            google_scholar on;
        }

    }
另外编译的时候需要添加ssl支持 https://github.com/cuber/ngx_http_google_filter_module/issues/114
